### PR TITLE
Fix getValue, processSetValueQueueItems uncachedValues check

### LINKED ISSUE #30: getValue() will never use the JSON handler to get a value
https://github.com/overhangio/openedx-scorm-xblock/blob/master/openedxscorm/static/js/src/scormxblock.js#L164-L173

The logical test uses `in` as in Python, but for JS this needs to be `uncachedValues.includes(cmi_element)`.

### PR DESCRIPTION
**Pull request by bryanlandia**
uncachedValues is an Array not Object so element membership needs to use Array.includes()

Fixes #30

### CODE REVIEW

**Review by regisb — APPROVED** [review]
Wow, that was a huge bug. Thanks for the PR!

**Comment by bryanlandia** [comment]
> Wow, that was a huge bug. Thanks for the PR!

Thanks Régis.  Crazy we or nobody else caught it before.

**Comment by bryanlandia** [comment]
@regisb Let me know if you might be able to cut a new release and push to PyPI.

**Comment by regisb** [comment]
v15.0.1 was just published to Pypi, along with [S3 storage support](https://github.com/overhangio/openedx-scorm-xblock/pull/29).

**Comment by regisb** [comment]
v16 indicates compatibility with Palm. The middle version number is for non-backward breaking changes. This xblock follows the same versioning scheme as Tutor: https://docs.tutor.overhang.io/tutor.html#versioning

**Pull request merged**
